version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
defaults: &defaults
  docker:
    - image: circleci/php:7.3-apache-stretch-node-browsers
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    - image: circleci/mysql:8.0.4
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
      environment:
        MYSQL_ROOT_PASSWORD: rootpw
        MYSQL_DATABASE: test_vardoc
        MYSQL_USER: user
        MYSQL_PASSWORD: passw0rd
  working_directory: /var/www/html/vardoc/docroot
commands:
  vardoc-build:
    steps:
      - checkout:
          path: /var/www/html/vardoc
      ## Setup Apache to point vardoc.test at /var/www/html/vardoc/docroot
      - run:
          name: Setup Apache to point vardoc.test at /var/www/html/vardoc/docroot
          command: |
            sudo cp /var/www/html/vardoc/.circleci/env/vardoc.test.conf /etc/apache2/sites-available/vardoc.test.conf
            sudo a2ensite vardoc.test
            sudo service apache2 restart
            echo 127.0.0.1 vardoc.test | sudo tee -a /etc/hosts

      ## Install Usefull must have utils for debugging with SSH into this box.
      - run:
          name: Install Usefull must have utils for debugging with SSH into this box
          command: |
            sudo apt -qq update && sudo apt -qqy upgrade
            sudo apt -yqq install vim links lynx git diffutils htop curl wget p7zip-full unzip zip sed gcc g++ make libfreetype6-dev libjpeg62-turbo-dev libpng-dev xvfb mysql-client
      ## Install PHP extra.
      - run:
          name: Install PHP extra
          command: |
            sudo apt update
            sudo apt install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
            sudo -E docker-php-ext-install zip
            sudo -E docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo -E docker-php-ext-install mbstring bcmath pdo_mysql
            sudo -E docker-php-ext-install gd
            sudo service apache2 restart

      ## Change PHP Configurations.
      - run:
          name: PHP Configurations
          command: |
            echo -e "memory_limit = -1" | sudo tee /usr/local/etc/php/php.ini > /dev/null
            sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            sudo service apache2 restart
      - restore_cache:
          keys:
            - v4-composer-cache

      ## Waiting for MySQL to be ready.
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      ## Install browser tools
      - browser-tools/install-browser-tools

      ## List tool version.
      - run:
          name: List tool version
          command: |
            php --version
            node --version
            java --version
            google-chrome --version
            chromedriver --version
            mysql --version

      ## Configure and run the virtual display.
      - run:
          name: Configure and run the virtual display
          command: |
            export DISPLAY=:99
            xvfb :99 -ac -screen 0 1366x768x24 &>/dev/null &
            sleep 3

      ## Run selenium standalone server.
      - run:
          name: Run selenium standalone server
          command: |
            if [[ ! -f /home/circleci/selenium-server-standalone-2.53.1.jar ]]; then wget -O /home/circleci/selenium-server-standalone-2.53.1.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar; fi
            cd /home/circleci/
            java -jar selenium-server-standalone-2.53.1.jar -port 4445 > /home/circleci/selenium.log
          background: true

      ## Update the composer
      - run:
          name: Update the composer
          command: |
            sudo composer self-update --2
            composer --version

      ## Build vardoc with the composer.
      - run:
          name: Build vardoc with the composer
          command: |
            cd /var/www/html/vardoc
            composer install --no-interaction -vvv
            git clone --branch 5.0.x https://github.com/vardot/vardoc.git /var/www/html/vardoc/docroot/profiles/vardoc
            sudo chmod 777 -R /var/www/html/vardoc
      - save_cache:
          key: v4-composer-cache
          paths:
            - ~/.composer/cache

      ## Update PATH to point at the composer bin in the project.
      - run:
          name: Update PATH to point at the composer bin in the project
          command: |
            echo 'export PATH=/var/www/html/vardoc/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      ## Create test vardoc MySQL database and drop old one if exists.
      - run:
          name: Create test vardoc MySQL database and drop old one if exists
          command: |
            mysql -h 127.0.0.1 -uuser -ppassw0rd -e "DROP DATABASE IF EXISTS test_vardoc;CREATE DATABASE test_vardoc;"

      ## Install vardoc with drush.
      - run:
          name: Install vardoc with drush
          no_output_timeout: 30m
          command: |
            cd /var/www/html/vardoc/docroot/
            drush site-install vardoc --yes --site-name='Vardoc Test'   --account-name=webmaster --account-pass=dD.123123ddd --account-mail=webmaster@vardot.com --db-url="mysql://user:passw0rd@127.0.0.1/test_vardoc" vardoc_extra_components.vardoc_demo=true varbase_development_tools.varbase_development=true
            drush config-set system.performance css.preprocess 0 --yes
            drush config-set system.performance js.preprocess 0 --yes
            drush config-set system.logging error_level all --yes
            drush cr

      ## Automated Functional Acceptance Testing - Step 1 init tests.
      - run:
          name: Automated Functional Acceptance Testing - Step 1 init tests
          no_output_timeout: 30m
          command: |
            cd /var/www/html/vardoc/docroot/profiles/vardoc
            behat --strict --no-snippets -f pretty -o std tests/features/vardoc/step1-init-tests/
jobs:
  vardoc-testing-01-website-base-requirements:
    <<: *defaults
    steps:
      - vardoc-build
       ## Automated Functional Acceptance Testing group - 01 website base requirements
      - run:
          name: Automated Functional Acceptance Testing group - 01 website base requirements
          no_output_timeout: 30m
          command: |
            cd /var/www/html/vardoc/docroot/profiles/vardoc
            behat --strict --no-snippets -f pretty -o std tests/features/vardoc/step2-apply-tests/01-website-base-requirements/
  vardoc-testing-02-user-management-03-admin-management:
    <<: *defaults
    steps:
      - vardoc-build
      ## Automated Functional Acceptance Testing group - 02 user management - 03 admin management
      - run:
          name: Automated Functional Acceptance Testing group - 02 user management - 03 admin management
          no_output_timeout: 30m
          command: |
            cd /var/www/html/vardoc/docroot/profiles/vardoc
            behat --strict --no-snippets -f pretty -o std tests/features/vardoc/step2-apply-tests/02-user-management/
            behat --strict --no-snippets -f pretty -o std tests/features/vardoc/step2-apply-tests/03-admin-management/
  vardoc-testing-04-content-structure:
    <<: *defaults
    steps:
      - vardoc-build
      ## Automated Functional Acceptance Testing group - 04 content structure
      - run:
          name: Automated Functional Acceptance Testing group - 04 content structure
          no_output_timeout: 30m
          command: |
            cd /var/www/html/vardoc/docroot/profiles/vardoc
            behat --strict --no-snippets -f pretty -o std tests/features/vardoc/step2-apply-tests/04-content-structure/
  vardoc-testing-05-content-management:
    <<: *defaults
    steps:
      - vardoc-build
      ## Automated Functional Acceptance Testing group - 05 content-management
      - run:
          name: Automated Functional Acceptance Testing group - 05 content-management
          no_output_timeout: 30m
          command: |
            cd /var/www/html/vardoc/docroot/profiles/vardoc
            behat --strict --no-snippets -f pretty -o std tests/features/vardoc/step2-apply-tests/05-content-management/

workflows:
  version: 2
  vardoc-workflow:
    jobs:
      - vardoc-testing-01-website-base-requirements:
          filters:
            tags:
              only: /^5.*/
            branches:
              only: /^5.0.x/
      - vardoc-testing-02-user-management-03-admin-management:
          filters:
            tags:
              only: /^5.*/
            branches:
              only: /^5.0.x/
      - vardoc-testing-04-content-structure:
          filters:
            tags:
              only: /^5.*/
            branches:
              only: /^5.0.x/
      - vardoc-testing-05-content-management:
          filters:
            tags:
              only: /^5.*/
            branches:
              only: /^5.0.x/